FROM ruby:3.2.2

# パッケージリストを更新し、nodejsとPostgreSQLクライアントをインストール
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client
WORKDIR /sample-app
COPY Gemfile /sample-app/Gemfile
COPY Gemfile.lock /sample-app/Gemfile.lock
RUN bundle install

# エントリーポイントスクリプト（コンテナ起動時に実行するスクリプト）をコピー
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# コンテナ起動時に実行されるデフォルトのコマンド（Railsサーバーの起動）
CMD ["rails", "server", "-b", "0.0.0.0"]